server:
  port: 8080

  # develop ??? ?
  #  port: 8080

  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  datasource:
    #     develop ??? ?
    #    driver-class-name: org.mariadb.jdbc.Driver
    #    url: jdbc:mariadb://i8a810.p.ssafy.io:3939/bundler?useUnicode=true&characterEncoding=utf-8
    #    username: root
    #    password: my-secret-pw

    # ssafy ??? local ?
    #        driver-class-name: org.mariadb.jdbc.Driver
    #        url: jdbc:mariadb://localhost:3306/bundler?useUnicode=true&characterEncoding=utf-8
    #        username: root
    #        password: ssafy

    #     ?? ??? local ?
    url: jdbc:mysql://localhost:3306/ddobagi?useUnicode=true&characterEncoding=utf-8
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

    # ??? dummy test ?
    #    driver-class-name: org.mariadb.jdbc.Driver
    #    url: jdbc:mariadb://i8a810.p.ssafy.io:3939/bundlerdummy?useUnicode=true&characterEncoding=utf-8
    #    username: root
    #    password: my-secret-pw

  output.ansi.enabled: always

  jpa:
    hibernate:
      ddl-auto: create # (1) ??? ?? ??
      use-new-id-generator-mappings: false
    show-sql: false # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true # (3) SQL pretty print

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

jwt:
  secret: n0syh2pcj1W9hGmeXsEFrfSiSqh3BE8ZOV4HOkAM2yFpFSQ9E3pWV4TQCgwvAmYaTveCepecwcZpBbFFdjfakskejrlfrpgodigksmsrjswlcka

